import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Fira_Sans } from "next/font/google"; //ESTA PARECE SER LA 2da. ELEGIDA
//import { Public_Sans } from "next/font/google"; //ESTA PARECE SER LA ELEGIDA
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Source_Sans_3 } from "next/font/google";
import { cn } from "@/lib/utils";

import { Instrument_Sans, Mulish, Noto_Sans_Mono } from "next/font/google";

import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const roboto = Source_Sans_3({
    weight: "400",
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Grupo Lotificadora",
    description: "Generated by Hexcode",
    authors: [
        {
            name: "hexcode",
            url: "https://hexcode.com.mx",
        },
    ],
    creator: "Daniel Alberto Bruno Reyna",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
            <body className={cn("min-h-svh bg-background font-sans antialiased", roboto.className)}>
                {/* <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange enableColorScheme> */}
                <ThemeProvider
                    attribute="class"
                    defaultTheme="light"
                    enableSystem
                    disableTransitionOnChange={false}
                    enableColorScheme
                    themes={["theme-gl-1", "theme-gl-2", "theme-azul", "theme-gl-3", "theme-naranja", "theme-bubblegum"]}
                >
                    <div vaul-drawer-wrapper="">
                        <div className="relative flex min-h-svh flex-col bg-background rounded-[0.5rem] border shadow ">{children}</div>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
